#!/usr/bin/env bash
# program_flash.sh — Program a bitstream into the on-board BPI flash via Vivado TCL
#
# The on-board flash is a Micron MT28GU512AAX1E (512 Mbit BPI x16, Mfg ID 0x89).
# Vivado's cfgmem part name: mt28gu512aax1e-bpi-x16
#
# Required sequence (discovered empirically, May 2026):
#   1. write_cfgmem: .bit -> .mcs (BPIx16, 512 Mb)
#   2. Load Vivado's bpi_xc7k480t_pullnone.bit helper into FPGA SRAM via JTAG
#      (this routes CCLK to the BPI flash bus via STARTUPE2, required for hw_manager)
#   3. create_hw_cfgmem with mt28gu512aax1e-bpi-x16
#   4. program_hw_cfgmem: erase + write + verify (~2 minutes at 15 MHz)
#
# Usage:
#   tool/hw/program_flash.sh [path/to/top_npu.bit]
#
# Defaults to:
#   ip/vivado/xc7k480t/npu_fpga/npu_fpga.runs/impl_1/top_npu.bit
#
# Prerequisites (dev host):
#   - FT4232H JTAG USB cable plugged in (lsusb shows 0403:6011)
#   - hw_server running on 127.0.0.1:3121 (Vivado 2025.2)
#   - ~/Xilinx/2025.2/Vivado/bin/vivado available (override via VIVADO env var)
#   - bpi_xc7k480t_pullnone.bit extracted from Vivado cfgmem zip (done automatically)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
VIVADO="${VIVADO:-$HOME/Xilinx/2025.2/Vivado/bin/vivado}"
HW_SERVER="${HW_SERVER:-localhost:3121}"
FLASH_PART="mt28gu512aax1e-bpi-x16"
BITFILE_ZIP="${VIVADO_CFGMEM_ZIP:-$(dirname "$(dirname "$VIVADO")")/data/xicom/cfgmem/bitfile.zip}"
HELPER_BIT="/tmp/bpi_xc7k480t_pullnone.bit"
TCL_SCRIPT="/tmp/program_flash_$$.tcl"

BITSTREAM="${1:-$REPO_ROOT/ip/vivado/xc7k480t/npu_fpga/npu_fpga.runs/impl_1/top_npu.bit}"
MCS_FILE="/tmp/$(basename "${BITSTREAM%.bit}").mcs"

# Validate
if [[ ! -f "$BITSTREAM" ]]; then
    echo "ERROR: bitstream not found: $BITSTREAM" >&2
    exit 1
fi
if [[ ! -x "$VIVADO" ]]; then
    echo "ERROR: vivado not found at $VIVADO. Set VIVADO env var to override." >&2
    exit 1
fi

echo "INFO: Bitstream : $BITSTREAM ($(du -sh "$BITSTREAM" | cut -f1))"
echo "INFO: Flash part: $FLASH_PART"
echo "INFO: hw_server : $HW_SERVER"
echo ""

# Extract BPI helper bitstream if not already present
if [[ ! -f "$HELPER_BIT" ]]; then
    echo "INFO: Extracting BPI helper bitstream from Vivado..."
    if [[ ! -f "$BITFILE_ZIP" ]]; then
        echo "ERROR: Vivado cfgmem bitfile.zip not found at $BITFILE_ZIP" >&2
        exit 1
    fi
    unzip -j "$BITFILE_ZIP" "bitfile/bpi_xc7k480t_pullnone.bit" -d /tmp/
    echo "INFO: Helper extracted: $HELPER_BIT"
fi

# Write TCL script
cat > "$TCL_SCRIPT" << TCLEOF
################################################################################
# Auto-generated by tool/hw/program_flash.sh
# Flash part: $FLASH_PART
# Bitstream:  $BITSTREAM
################################################################################

set HELPER_BIT {$HELPER_BIT}
set BIT        {$BITSTREAM}
set MCS        {$MCS_FILE}
set PART       {$FLASH_PART}

# Step 1: Generate MCS
# The bitstream uses Vivado's SPIx1 default mode (no CONFIG_MODE=BPI16 in XDC)
# so write_cfgmem must also use SPIx1 interface. The flash hardware is BPI16,
# but the cfgmem interface flag describes how the bitstream was generated, not
# how the flash is wired. Using SPIx1 here produces a correct MCS for BPI flash.
# The BPI helper bitstream (step 3) ensures CCLK reaches the BPI bus.
puts "=== Step 1: write_cfgmem ==="
write_cfgmem \\
    -format    mcs \\
    -interface SPIx1 \\
    -size      64 \\
    -loadbit   "up 0x00000000 \$BIT" \\
    -force \\
    -file      \$MCS
puts "INFO: MCS = \$MCS ([file size \$MCS] bytes)"

# Step 2: Connect
open_hw_manager
connect_hw_server -url $HW_SERVER -allow_non_jtag
current_hw_target [lindex [get_hw_targets] 0]
set_property PARAM.FREQUENCY 15000000 [current_hw_target]
open_hw_target
current_hw_device [lindex [get_hw_devices xc7k480t_0] 0]
refresh_hw_device -update_hw_probes false [current_hw_device]
puts "INFO: device = [current_hw_device]"

# Step 3: Load BPI helper into FPGA SRAM (routes CCLK to BPI flash via STARTUPE2)
puts "=== Step 3: load BPI helper into SRAM ==="
set_property PROBES.FILE      {} [current_hw_device]
set_property FULL_PROBES.FILE {} [current_hw_device]
set_property PROGRAM.FILE     \$HELPER_BIT [current_hw_device]
program_hw_devices [current_hw_device]
refresh_hw_device  [current_hw_device]
puts "INFO: BPI helper loaded ([current_hw_device])"

# Step 4: Create cfgmem
puts "=== Step 4: create_hw_cfgmem ==="
create_hw_cfgmem \\
    -hw_device [current_hw_device] \\
    -mem_dev   [lindex [get_cfgmem_parts \$PART] 0]
set CM [get_property PROGRAM.HW_CFGMEM [current_hw_device]]
set_property PROGRAM.BLANK_CHECK  0      \$CM
set_property PROGRAM.ERASE        1      \$CM
set_property PROGRAM.CFG_PROGRAM  1      \$CM
set_property PROGRAM.VERIFY       1      \$CM
set_property PROGRAM.FILES        \$MCS  \$CM

# Step 5: Erase + program + verify
puts "=== Step 5: program_hw_cfgmem (erase + write + verify, ~2 min) ==="
program_hw_cfgmem -hw_cfgmem \$CM
puts ""
puts "*** FLASH PROGRAMMING COMPLETE ***"

close_hw_target
disconnect_hw_server
close_hw_manager
TCLEOF

echo "INFO: Running Vivado batch flash programming..."
"$VIVADO" -mode batch \
    -source "$TCL_SCRIPT" \
    -journal "/tmp/program_flash_$$.jou" \
    -log     "/tmp/program_flash_$$.log"

RC=$?
if grep -q "FLASH PROGRAMMING COMPLETE" "/tmp/program_flash_$$.log" 2>/dev/null; then
    echo ""
    echo "SUCCESS: Flash programmed and verified."
    echo "  Log: /tmp/program_flash_$$.log"
    echo ""
    echo "NOTE: Cold-boot PCIe link training is unreliable on this AMD FCH host."
    echo "      After power-cycling the FPGA board, use the JTAG SRAM bring-up flow:"
    echo "        tool/hw/reboot_and_load.sh"
else
    echo ""
    echo "ERROR: Flash programming may have failed. Check log:"
    echo "  /tmp/program_flash_$$.log"
    grep -E "ERROR|FAIL|27-3347|27-2251" "/tmp/program_flash_$$.log" 2>/dev/null || true
    exit 1
fi

rm -f "$TCL_SCRIPT"
