name: Chisel CI
on:
  push:
    branches:
      - main
      - releases/**
  pull_request:
    branches:
      - main
      - 'releases/**'

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  Build:
    runs-on: ubuntu-latest
    needs: Lint
    container:
      image: fangruil/chisel-dev:amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: sbt run

  Test:
    runs-on: ubuntu-latest
    needs: Build
    container:
      image: fangruil/chisel-dev:amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: sbt test
